CREATE DATABASE blog;

CREATE TABLE novoblog(
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    titulodoblog  VARCHAR(50) NOT NULL,
    textocurtodoblog VARCHAR(10) UNIQUE NOT NULL,
    conteudoblog VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);